name: format-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check formatting with black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"
