name: lint

on:
  push:
    branches:
      - main

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pylint
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pylint --rcfile=.pylintrc src/