name: lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Run pylint
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip install -r requirements.txt && pylint --rcfile=.pylintrc src/